
    create table Accesorio (
        id bigint not null,
        personaje_id bigint,
        primary key (id)
    )

    create table Arma (
        ataque integer not null,
        defensa integer not null,
        id bigint not null,
        personaje_id bigint,
        primary key (id)
    )

    create table BolsaDeMoneda (
        monedas integer not null,
        id bigint not null,
        primary key (id)
    )

    create table Item (
        id bigint generated by default as identity (start with 1),
        costo integer not null,
        nombre varchar(255),
        personaje_duenio_id bigint,
        ubicacion_id bigint,
        primary key (id)
    )

    create table Personajes (
        id bigint generated by default as identity (start with 1),
        monedas integer not null,
        nombre varchar(255),
        tipoDePersonaje varchar(255),
        primary key (id)
    )

    create table Personajes_Ubicacion (
        Personajes_id bigint not null,
        ubicaciones_id bigint not null,
        ubicacion_visitada integer not null,
        primary key (Personajes_id, ubicacion_visitada)
    )

    create table Regalo (
        fraseMotivacional varchar(255),
        id bigint not null,
        primary key (id)
    )

    create table Ubicacion (
        id bigint generated by default as identity (start with 1),
        nivel integer not null,
        x integer not null,
        y integer not null,
        nombre varchar(255),
        primary key (id)
    )

    alter table Accesorio 
        add constraint FK_tdgnmmp4k304yqhn3y37cp2i8 
        foreign key (id) 
        references Item

    alter table Accesorio 
        add constraint FK_jajcmson3j1ocxa0egcbwsao2 
        foreign key (personaje_id) 
        references Personajes

    alter table Arma 
        add constraint FK_fcdyilcovp8fdmvh20qbxflwr 
        foreign key (id) 
        references Item

    alter table Arma 
        add constraint FK_9nqlrv8niusrkv8xq9m0c7epw 
        foreign key (personaje_id) 
        references Personajes

    alter table BolsaDeMoneda 
        add constraint FK_f2ylun97qhldtuhjuxi0eubv1 
        foreign key (id) 
        references Item

    alter table Item 
        add constraint FK_3t7895j7kgbg00t6legj01yi5 
        foreign key (personaje_duenio_id) 
        references Personajes

    alter table Item 
        add constraint FK_kfrwufil16ll89iweov1l6579 
        foreign key (ubicacion_id) 
        references Ubicacion

    alter table Personajes_Ubicacion 
        add constraint FK_157bu6gfy3mw8isr6xo05po65 
        foreign key (ubicaciones_id) 
        references Ubicacion

    alter table Personajes_Ubicacion 
        add constraint FK_nlqkytaygw1foisnbcy3ljqda 
        foreign key (Personajes_id) 
        references Personajes

    alter table Regalo 
        add constraint FK_347m6xm8qomwlctni9npcilaf 
        foreign key (id) 
        references Item
